import asyncio
import json
import logging
import os
import re
import tempfile
from pathlib import Path

from app.services.gemini_client import generate_gemini_content, image_part
from PIL import Image

from app.core.config import settings

logger = logging.getLogger(__name__)

MOCK_MARKER = "detailed description of the extracted image generated by a Vision-Language Model"

# When Gemini free-tier daily quota is gone, stop all vision calls for this process.
_VISION_QUOTA_TRIPPED = False


def vision_quota_tripped() -> bool:
    return _VISION_QUOTA_TRIPPED


def _trip_vision_quota(reason: str) -> None:
    global _VISION_QUOTA_TRIPPED
    if not _VISION_QUOTA_TRIPPED:
        _VISION_QUOTA_TRIPPED = True
        logger.error(
            "Gemini Vision quota exhausted — skipping further vision labels (%s)",
            reason[:160],
        )


def _is_daily_quota_error(err: str) -> bool:
    low = (err or "").lower()
    return (
        "generate_content_free_tier" in low
        or "perdayperproject" in low
        or "quota value': '20'" in low
        or "quotaValue': '20'" in err
    )

DESCRIBE_PROMPT = """Describe this Hindi Pathmala textbook illustration in 1-2 sentences.
Use Hindi or English name for the main subject (person, animal, object, scene, diagram).
Output ONLY the description."""

LABEL_PROMPT = """Identify this Hindi Pathmala textbook illustration. Reply with ONLY a short proper name (2-5 words) in Hindi Devanagari.

Rules:
- MUST be Hindi Devanagari only (माँ और बेटा, पेड़ पर बंदर, नीम का पेड़, पुलिस और चोर).
- NEVER use English words (not "Mother and Son", "Boy Studying", "Police").
- Famous person → Hindi spelling of the name.
- NEVER describe clothes, pose, glasses, saree, cap, smile, or camera angle.
- NEVER write "man/woman/person/boy/girl in/with ...".
No punctuation, no English, no extra text."""

LABEL_PROMPT_HINDI_STRICT = """यह हिंदी पाठ्यपुस्तक का चित्र है। केवल 2–5 शब्दों का हिंदी (देवनागरी) नाम लिखें।
अंग्रेज़ी शब्द बिल्कुल न लिखें। केवल नाम — कोई वाक्य नहीं।
उदाहरण: माँ और बेटा, पेड़ पर बंदर, मेज़ पर पढ़ता लड़का, पुलिस चोर का पीछा"""


GENERIC_APPEARANCE_RE = re.compile(
    r"\b(man|woman|person|boy|girl|lady|gentleman|athlete|player|"
    r"child|kid|male|female)\b.+\b(in|with|wearing|holding|smiling|"
    r"glasses|saree|sari|cap|hat|medal|shirt|dress|turban)\b",
    re.I,
)
POSE_TAIL_RE = re.compile(
    r"\s+(smiling|standing|sitting|wearing.+|in a .+|with glasses|"
    r"with a medal|holding.+)$",
    re.I,
)


def is_placeholder_description(desc: str | None) -> bool:
    if not desc or not desc.strip():
        return True
    low = desc.strip().lower()
    if "manual import" in low or "[no vlm" in low:
        return True
    if low.startswith("[ocr:") or "no text on figure" in low:
        return True
    if MOCK_MARKER in desc:
        return True
    # Short Devanagari names (आम, मोर, कमल) are real picture-match labels.
    stripped = desc.strip()
    if len(stripped) < 12:
        if any("\u0900" <= c <= "\u097F" for c in stripped) and len(stripped) >= 2:
            return False
        return True
    return False


def _mime_for_path(image_path: str) -> str:
    ext = Path(image_path).suffix.lower()
    return {
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".webp": "image/webp",
        ".gif": "image/gif",
    }.get(ext, "image/png")


async def _vision_call(image_path: str, prompt: str, *, retries: int = 3) -> str:
    if _VISION_QUOTA_TRIPPED:
        return ""
    if not settings.GEMINI_API_KEY:
        return ""

    path = Path(image_path)
    if not path.is_file():
        return ""

    image_bytes = path.read_bytes()
    last_err: Exception | None = None
    # Daily quota never recovers mid-run — at most one attempt, then trip.
    max_attempts = 1 if retries < 1 else min(retries, 2)
    for attempt in range(max_attempts):
        if _VISION_QUOTA_TRIPPED:
            return ""
        try:
            response = await asyncio.wait_for(
                generate_gemini_content(
                    [
                        prompt,
                        image_part(image_bytes, _mime_for_path(image_path)),
                    ]
                ),
                timeout=45,
            )
            return (response.text or "").strip()
        except Exception as e:
            last_err = e
            err = str(e)
            if "429" in err or "RESOURCE_EXHAUSTED" in err:
                if _is_daily_quota_error(err):
                    _trip_vision_quota(err)
                    return ""
                # Short-lived rate limit: one brief pause only
                if attempt + 1 < max_attempts:
                    wait = 8
                    logger.warning(
                        "Vision rate-limit %s/%s for %s — wait %ss",
                        attempt + 1,
                        max_attempts,
                        image_path,
                        wait,
                    )
                    await asyncio.sleep(wait)
                    continue
                return ""
            if "503" in err or "UNAVAILABLE" in err:
                if attempt + 1 < max_attempts:
                    await asyncio.sleep(5)
                    continue
                return ""
            logger.error("Vision API error for %s: %s", image_path, e)
            return ""
    logger.error("Vision API failed for %s after retries: %s", image_path, last_err)
    return ""

async def analyze_image_with_vlm(image_path: str) -> str:
    """Full description of a textbook figure — used during PDF ingestion."""
    result = await _vision_call(image_path, DESCRIBE_PROMPT)
    return result or "Textbook illustration"


_JUNK_LABEL_RE = re.compile(
    r"^(?:page\s*\d+(?:\s*fig\s*\d+)?|fig\s*\d+|figure\s*\d+|pdf\d+|p\d+_img\d+)$",
    re.I,
)


def is_generic_appearance_label(label: str) -> bool:
    """'Man with glasses' is not a usable match label."""
    s = (label or "").strip()
    if not s:
        return True
    if GENERIC_APPEARANCE_RE.search(s):
        return True
    low = s.lower()
    if low.startswith(
        (
            "man ",
            "woman ",
            "person ",
            "a man",
            "a woman",
            "the man",
            "the woman",
            "athlete ",
        )
    ):
        return True
    return False


def is_junk_label(label: str) -> bool:
    """Student-facing labels must not be file names, page codes, or clothing descriptions."""
    s = (label or "").strip()
    if not s or len(s) < 2:
        return True
    low = s.lower()
    if low in ("figure", "textbook illustration", "picture", "item"):
        return True
    if _JUNK_LABEL_RE.match(low):
        return True
    if re.match(r"^page\d+\s*fig\d+", low):
        return True
    if is_generic_appearance_label(s):
        return True
    if low.startswith("[ocr:") or "no text on figure" in low:
        return True
    return False


def normalize_short_label(label: str) -> str:
    label = (label or "").split("\n")[0].strip().strip('"').strip("'").strip(".")
    label = POSE_TAIL_RE.sub("", label).strip()
    if len(label) > 60:
        label = label[:57] + "..."
    if is_junk_label(label):
        return ""
    return label or ""


def is_narrative_vlm_description(desc: str) -> bool:
    """Long generic VLM sentences are bad match labels."""
    if not desc or len(desc.strip()) < 8:
        return True
    lower = desc.strip().lower()
    return lower.startswith(
        (
            "the illustration",
            "this illustration",
            "the image",
            "this image",
            "the picture",
            "this picture",
            "the photo",
        )
    )


def heuristic_short_label_from_description(desc: str) -> str:
    """Best-effort name extraction without calling the API."""
    desc = (desc or "").strip()
    if not desc:
        return ""
    if not is_narrative_vlm_description(desc) and len(desc.split()) <= 6:
        return normalize_short_label(desc)
    patterns = (
        r"portrait of (?:the )?([A-Za-z][^.,\"]{2,40})",
        r"features (?:the )?([A-Z][^.,\"]{2,40})",
        r"depicts (?:the )?([A-Z][^.,\"]{2,40})",
        r"shows (?:the )?([A-Z][^.,\"]{2,40})",
        r"subject is ([A-Za-z][^.,\"]{2,40})",
        r"of ([A-Z][a-z]+(?: [A-Z][a-z]+)+)",
    )
    for pat in patterns:
        m = re.search(pat, desc)
        if m:
            return normalize_short_label(m.group(1).strip())
    return ""


async def short_label_for_image(image_path: str, *, hindi_only: bool = False) -> str:
    """Short 2-5 word label for picture-match questions."""
    prompt = LABEL_PROMPT_HINDI_STRICT if hindi_only else LABEL_PROMPT
    label = await _vision_call(image_path, prompt)
    return normalize_short_label(label) if label else ""


async def short_label_for_image_lowmem(
    image_path: str, max_px: int = 512, *, hindi_only: bool = False
) -> str:
    """Vision labels using a small JPEG — safe on 1GB hosts when run one image at a time."""
    path = Path(image_path)
    if not path.is_file():
        return ""
    tmp_path: str | None = None
    try:
        with Image.open(path) as im:
            im = im.convert("RGB")
            im.thumbnail((max_px, max_px))
            fd, tmp_path = tempfile.mkstemp(suffix=".jpg")
            os.close(fd)
            im.save(tmp_path, "JPEG", quality=85, optimize=True)
        prompt = LABEL_PROMPT_HINDI_STRICT if hindi_only else LABEL_PROMPT
        label = await _vision_call(tmp_path, prompt)
        return normalize_short_label(label) if label else ""
    except Exception as e:
        logger.error("Low-mem vision label failed for %s: %s", image_path, e)
        return ""
    finally:
        if tmp_path and os.path.isfile(tmp_path):
            try:
                os.unlink(tmp_path)
            except OSError:
                pass


async def short_labels_from_metadata(
    items: list[tuple[str, str]],
) -> list[str]:
    """
    Text-only labels for picture match when vision is skipped (low memory).
    Each item is (filename_hint, stored_description).
    """
    n = len(items)
    if n == 0:
        return []

    heuristics = [
        heuristic_short_label_from_description(desc)
        for _, desc in items
    ]

    if not settings.GEMINI_API_KEY:
        return [h for h in heuristics if h and not is_junk_label(h)]

    lines = []
    for i, (_, desc) in enumerate(items, start=1):
        if desc and not is_placeholder_description(desc):
            body = desc.strip()
        else:
            body = "(no description stored — infer from typical Class 1 textbook figure)"
        lines.append(f"{i}. {body[:350]}")

    prompt = (
        f"Give the official name for each numbered textbook figure (2-5 words).\n"
        f"Famous people must be named (Narendra Modi, Amitabh Bachchan, Virat Kohli).\n"
        f"Never describe clothes, glasses, saree, cap, smile, or 'man/woman in…'.\n"
        f"Return JSON only: {{\"labels\": [ ... ]}} with exactly {n} strings in order.\n\n"
        + "\n".join(lines)
    )

    try:
        response = await asyncio.wait_for(
            generate_gemini_content(
                prompt,
                config={"response_mime_type": "application/json"},
            ),
            timeout=45,
        )
        data = json.loads(response.text or "{}")
        labels = data.get("labels") or []
        out: list[str] = []
        for i in range(n):
            raw = labels[i] if i < len(labels) else ""
            lbl = normalize_short_label(str(raw)) if raw else ""
            if not lbl or is_narrative_vlm_description(lbl):
                lbl = heuristics[i] or ""
            out.append(lbl)
        return out
    except Exception as e:
        logger.error("Text label batch failed: %s", e)
        return [heuristics[i] or "" for i in range(n)]


async def enrich_picture_match_labels(
    labels: list[str],
    images: list[dict],
) -> list[str]:
    """Replace junk/empty labels using descriptions, then low-res vision."""
    n = len(images)
    out = [(normalize_short_label(lbl) if lbl else "") for lbl in labels[:n]]
    while len(out) < n:
        out.append("")

    for i in range(n):
        if out[i] and not is_junk_label(out[i]):
            continue
        desc = (images[i].get("description") or images[i].get("caption") or "").strip()
        if desc and not is_placeholder_description(desc):
            h = heuristic_short_label_from_description(desc)
            if h and not is_junk_label(h):
                out[i] = h
                continue
        path = images[i].get("image_path")
        if path and os.path.isfile(path) and settings.GEMINI_API_KEY:
            v = await short_label_for_image_lowmem(path)
            if v and not is_junk_label(v):
                out[i] = v

    missing = [i for i in range(n) if not out[i] or is_junk_label(out[i])]
    if missing and settings.GEMINI_API_KEY:
        lines = []
        for idx in missing:
            desc = (images[idx].get("description") or images[idx].get("caption") or "").strip()
            body = (
                desc[:350]
                if desc and not is_placeholder_description(desc)
                else "Unknown textbook photo — infer a specific 2-5 word name"
            )
            lines.append(f"{len(lines) + 1}. {body}")
        if lines:
            prompt = (
                f"Give the official proper name for each numbered figure "
                f"(full person name, monument, food). Never describe clothing. "
                f"JSON: {{\"labels\": [...]}} with exactly {len(lines)} strings.\n\n"
                + "\n".join(lines)
            )
            try:
                response = await asyncio.wait_for(
                    generate_gemini_content(
                        prompt,
                        config={"response_mime_type": "application/json"},
                    ),
                    timeout=45,
                )
                data = json.loads(response.text or "{}")
                extra = data.get("labels") or []
                for j, img_idx in enumerate(missing[: len(extra)]):
                    lbl = normalize_short_label(str(extra[j]))
                    if lbl and not is_junk_label(lbl):
                        out[img_idx] = lbl
            except Exception as e:
                logger.error("Picture label retry LLM failed: %s", e)

    for i in range(n):
        if not out[i] or is_junk_label(out[i]):
            out[i] = f"Picture {i + 1}"
    return out
