import asyncio
import json
import logging
import os
import re
import tempfile
from pathlib import Path

import google.generativeai as genai
from PIL import Image

from app.core.config import settings

logger = logging.getLogger(__name__)

MOCK_MARKER = "detailed description of the extracted image generated by a Vision-Language Model"

DESCRIBE_PROMPT = """Describe this textbook illustration in 1-2 sentences.
Name the main subject clearly (person, animal, plant, object, or diagram).
Output ONLY the description."""

LABEL_PROMPT = """Identify this textbook photo. Reply with ONLY the proper name (2-5 words).

Rules:
- Famous person → full name (Narendra Modi, Amitabh Bachchan, Virat Kohli, Droupadi Murmu, P V Sindhu).
- Famous place/monument → official name (Taj Mahal, Red Fort, Golden Temple).
- Food/object → common name (Samosa, Pani Puri).
- NEVER describe clothes, pose, glasses, saree, cap, smile, medal, or camera angle.
- NEVER write "man/woman/person/athlete in/with ...".
No punctuation, no extra text."""

GENERIC_APPEARANCE_RE = re.compile(
    r"\b(man|woman|person|boy|girl|lady|gentleman|athlete|player|"
    r"child|kid|male|female)\b.+\b(in|with|wearing|holding|smiling|"
    r"glasses|saree|sari|cap|hat|medal|shirt|dress|turban)\b",
    re.I,
)
POSE_TAIL_RE = re.compile(
    r"\s+(smiling|standing|sitting|wearing.+|in a .+|with glasses|"
    r"with a medal|holding.+)$",
    re.I,
)


def is_placeholder_description(desc: str | None) -> bool:
    if not desc or not desc.strip():
        return True
    return MOCK_MARKER in desc or len(desc.strip()) < 12


def _mime_for_path(image_path: str) -> str:
    ext = Path(image_path).suffix.lower()
    return {
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".webp": "image/webp",
        ".gif": "image/gif",
    }.get(ext, "image/png")


async def _vision_call(image_path: str, prompt: str) -> str:
    if not settings.GEMINI_API_KEY:
        return ""

    path = Path(image_path)
    if not path.is_file():
        return ""

    try:
        genai.configure(api_key=settings.GEMINI_API_KEY)
        model = genai.GenerativeModel(settings.LLM_MODEL)
        image_bytes = path.read_bytes()
        response = await asyncio.wait_for(
            model.generate_content_async(
                [
                    prompt,
                    {"mime_type": _mime_for_path(image_path), "data": image_bytes},
                ]
            ),
            timeout=45,
        )
        return (response.text or "").strip()
    except Exception as e:
        logger.error("Vision API error for %s: %s", image_path, e)
        return ""


async def analyze_image_with_vlm(image_path: str) -> str:
    """Full description of a textbook figure — used during PDF ingestion."""
    result = await _vision_call(image_path, DESCRIBE_PROMPT)
    return result or "Textbook illustration"


_JUNK_LABEL_RE = re.compile(
    r"^(?:page\s*\d+(?:\s*fig\s*\d+)?|fig\s*\d+|figure\s*\d+|pdf\d+|p\d+_img\d+)$",
    re.I,
)


def is_generic_appearance_label(label: str) -> bool:
    """'Man with glasses' is not a usable match label."""
    s = (label or "").strip()
    if not s:
        return True
    if GENERIC_APPEARANCE_RE.search(s):
        return True
    low = s.lower()
    if low.startswith(
        (
            "man ",
            "woman ",
            "person ",
            "a man",
            "a woman",
            "the man",
            "the woman",
            "athlete ",
        )
    ):
        return True
    return False


def is_junk_label(label: str) -> bool:
    """Student-facing labels must not be file names, page codes, or clothing descriptions."""
    s = (label or "").strip()
    if not s or len(s) < 2:
        return True
    low = s.lower()
    if low in ("figure", "textbook illustration", "picture", "item"):
        return True
    if _JUNK_LABEL_RE.match(low):
        return True
    if re.match(r"^page\d+\s*fig\d+", low):
        return True
    if is_generic_appearance_label(s):
        return True
    return False


def normalize_short_label(label: str) -> str:
    label = (label or "").split("\n")[0].strip().strip('"').strip("'").strip(".")
    label = POSE_TAIL_RE.sub("", label).strip()
    if len(label) > 60:
        label = label[:57] + "..."
    if is_junk_label(label):
        return ""
    return label or ""


def is_narrative_vlm_description(desc: str) -> bool:
    """Long generic VLM sentences are bad match labels."""
    if not desc or len(desc.strip()) < 8:
        return True
    lower = desc.strip().lower()
    return lower.startswith(
        (
            "the illustration",
            "this illustration",
            "the image",
            "this image",
            "the picture",
            "this picture",
            "the photo",
        )
    )


def heuristic_short_label_from_description(desc: str) -> str:
    """Best-effort name extraction without calling the API."""
    desc = (desc or "").strip()
    if not desc:
        return ""
    if not is_narrative_vlm_description(desc) and len(desc.split()) <= 6:
        return normalize_short_label(desc)
    patterns = (
        r"portrait of (?:the )?([A-Za-z][^.,\"]{2,40})",
        r"features (?:the )?([A-Z][^.,\"]{2,40})",
        r"depicts (?:the )?([A-Z][^.,\"]{2,40})",
        r"shows (?:the )?([A-Z][^.,\"]{2,40})",
        r"subject is ([A-Za-z][^.,\"]{2,40})",
        r"of ([A-Z][a-z]+(?: [A-Z][a-z]+)+)",
    )
    for pat in patterns:
        m = re.search(pat, desc)
        if m:
            return normalize_short_label(m.group(1).strip())
    return ""


async def short_label_for_image(image_path: str) -> str:
    """Short 2-5 word label for picture-match questions."""
    label = await _vision_call(image_path, LABEL_PROMPT)
    return normalize_short_label(label) if label else ""


async def short_label_for_image_lowmem(image_path: str, max_px: int = 512) -> str:
    """Vision labels using a small JPEG — safe on 1GB hosts when run one image at a time."""
    path = Path(image_path)
    if not path.is_file():
        return ""
    tmp_path: str | None = None
    try:
        with Image.open(path) as im:
            im = im.convert("RGB")
            im.thumbnail((max_px, max_px))
            fd, tmp_path = tempfile.mkstemp(suffix=".jpg")
            os.close(fd)
            im.save(tmp_path, "JPEG", quality=85, optimize=True)
        label = await _vision_call(tmp_path, LABEL_PROMPT)
        return normalize_short_label(label) if label else ""
    except Exception as e:
        logger.error("Low-mem vision label failed for %s: %s", image_path, e)
        return ""
    finally:
        if tmp_path and os.path.isfile(tmp_path):
            try:
                os.unlink(tmp_path)
            except OSError:
                pass


async def short_labels_from_metadata(
    items: list[tuple[str, str]],
) -> list[str]:
    """
    Text-only labels for picture match when vision is skipped (low memory).
    Each item is (filename_hint, stored_description).
    """
    n = len(items)
    if n == 0:
        return []

    heuristics = [
        heuristic_short_label_from_description(desc)
        for _, desc in items
    ]

    if not settings.GEMINI_API_KEY:
        return [h for h in heuristics if h and not is_junk_label(h)]

    lines = []
    for i, (_, desc) in enumerate(items, start=1):
        if desc and not is_placeholder_description(desc):
            body = desc.strip()
        else:
            body = "(no description stored — infer from typical Class 1 textbook figure)"
        lines.append(f"{i}. {body[:350]}")

    prompt = (
        f"Give the official name for each numbered textbook figure (2-5 words).\n"
        f"Famous people must be named (Narendra Modi, Amitabh Bachchan, Virat Kohli).\n"
        f"Never describe clothes, glasses, saree, cap, smile, or 'man/woman in…'.\n"
        f"Return JSON only: {{\"labels\": [ ... ]}} with exactly {n} strings in order.\n\n"
        + "\n".join(lines)
    )

    try:
        genai.configure(api_key=settings.GEMINI_API_KEY)
        model = genai.GenerativeModel(settings.LLM_MODEL)
        response = await asyncio.wait_for(
            model.generate_content_async(
                prompt,
                generation_config=genai.GenerationConfig(
                    response_mime_type="application/json",
                ),
            ),
            timeout=45,
        )
        data = json.loads(response.text or "{}")
        labels = data.get("labels") or []
        out: list[str] = []
        for i in range(n):
            raw = labels[i] if i < len(labels) else ""
            lbl = normalize_short_label(str(raw)) if raw else ""
            if not lbl or is_narrative_vlm_description(lbl):
                lbl = heuristics[i] or ""
            out.append(lbl)
        return out
    except Exception as e:
        logger.error("Text label batch failed: %s", e)
        return [heuristics[i] or "" for i in range(n)]


async def enrich_picture_match_labels(
    labels: list[str],
    images: list[dict],
) -> list[str]:
    """Replace junk/empty labels using descriptions, then low-res vision."""
    n = len(images)
    out = [(normalize_short_label(lbl) if lbl else "") for lbl in labels[:n]]
    while len(out) < n:
        out.append("")

    for i in range(n):
        if out[i] and not is_junk_label(out[i]):
            continue
        desc = (images[i].get("description") or images[i].get("caption") or "").strip()
        h = heuristic_short_label_from_description(desc)
        if h and not is_junk_label(h):
            out[i] = h
            continue
        path = images[i].get("image_path")
        if path and os.path.isfile(path) and settings.GEMINI_API_KEY:
            v = await short_label_for_image_lowmem(path)
            if v and not is_junk_label(v):
                out[i] = v

    missing = [i for i in range(n) if not out[i] or is_junk_label(out[i])]
    if missing and settings.GEMINI_API_KEY:
        lines = []
        for idx in missing:
            desc = (images[idx].get("description") or images[idx].get("caption") or "").strip()
            body = (
                desc[:350]
                if desc and not is_placeholder_description(desc)
                else "Unknown textbook photo — infer a specific 2-5 word name"
            )
            lines.append(f"{len(lines) + 1}. {body}")
        if lines:
            prompt = (
                f"Give the official proper name for each numbered figure "
                f"(full person name, monument, food). Never describe clothing. "
                f"JSON: {{\"labels\": [...]}} with exactly {len(lines)} strings.\n\n"
                + "\n".join(lines)
            )
            try:
                genai.configure(api_key=settings.GEMINI_API_KEY)
                model = genai.GenerativeModel(settings.LLM_MODEL)
                response = await asyncio.wait_for(
                    model.generate_content_async(
                        prompt,
                        generation_config=genai.GenerationConfig(
                            response_mime_type="application/json",
                        ),
                    ),
                    timeout=45,
                )
                data = json.loads(response.text or "{}")
                extra = data.get("labels") or []
                for j, img_idx in enumerate(missing[: len(extra)]):
                    lbl = normalize_short_label(str(extra[j]))
                    if lbl and not is_junk_label(lbl):
                        out[img_idx] = lbl
            except Exception as e:
                logger.error("Picture label retry LLM failed: %s", e)

    for i in range(n):
        if not out[i] or is_junk_label(out[i]):
            out[i] = f"Picture {i + 1}"
    return out
